### ISSUE TITLE
cannot start mariadb service

### ISSUE THREAD

**Issue by gzsmhf** [gdraheim/docker-systemctl-replacement#92] opened 2020-04-10 13:17 UTC
when using it in WSL to start mariadb for the first time, it is fine. but after restart wsl, it cannot start mariadb. it doesn`t have any response when process 'systemctl start mariadb'. Here is ps -ef info:
root       337     9  0 23:01 tty1     00:00:00 /usr/bin/python /usr/bin/systemctl start mariadb
mysql      372   337  0 23:01 ?        00:00:00 [mysqld_safe] <defunct>
mysql      536   337  0 23:01 tty1     00:00:01 /bin/sh /usr/libexec/mariadb-wait-ready 372
root       603     1  0 23:02 tty2     00:00:00 /init ro
root       604   603  0 23:02 tty2     00:00:00 -bash
mysql     1868   536  0 23:05 tty1     00:00:00 sleep 1
root      1869   604  0 23:05 tty2     00:00:00 ps -ef

Then I have to ctrl+c to stop the command, it show the errors below:
^CTraceback (most recent call last):
  File "/usr/bin/systemctl", line 4527, in <module>
    result = command_func(*modules)
  File "/usr/bin/systemctl", line 1760, in start_modules
    return self.start_units(units, init) and found_all
  File "/usr/bin/systemctl", line 1770, in start_units
    if not self.start_unit(unit):
  File "/usr/bin/systemctl", line 1788, in start_unit
    return self.start_unit_from(conf)
  File "/usr/bin/systemctl", line 1798, in start_unit_from
    return self.do_start_unit_from(conf)
  File "/usr/bin/systemctl", line 2025, in do_start_unit_from
    run = subprocess_waitpid(forkpid)
  File "/usr/bin/systemctl", line 617, in subprocess_waitpid
    run_pid, run_stat = os.waitpid(pid, 0)

Only start mariadb service could cause this error, starting other services like nginx is ok.

**Comment by gdraheim** [comment] 2020-04-11 23:09
Please create a file /var/log/systemctl.debug.log before running the systemctl command.

This should allow you to see which "pid" it is actually waiting for. I assume that it is a Type=forking service, isn't it?

**Comment by gzsmhf** [comment] 2020-04-12 03:16
> 
> 
> Please create a file /var/log/systemctl.debug.log before running the systemctl command.
> 
> This should allow you to see which "pid" it is actually waiting for. I assume that it is a Type=forking service, isn't it?

Here are debug info:

INFO:systemctl:EXEC BEGIN /usr/bin/systemctl start mariadb --system
DEBUG:systemctl:======= systemctl.py start mariadb
DEBUG:systemctl:found 171 sysd files
DEBUG:systemctl:found 1 sysv files
INFO:systemctl:system is offline
DEBUG:systemctl:/usr/lib/systemd/system/mariadb.service no --user mode >> accept
DEBUG:systemctl:[34] 0. trying mariadb.service.lock _______
DEBUG:systemctl:[34] 0. holding lock on mariadb.service.lock
DEBUG:systemctl: start unit mariadb.service => /usr/lib/systemd/system/mariadb.service
DEBUG:systemctl:extra-vars []
DEBUG:systemctl:can not expand $MAINPID
DEBUG:systemctl:no status file: /var/run/mariadb.service.status
 returning {}
INFO:systemctl: pre-start '/usr/libexec/mariadb-prepare-db-dir' 'mariadb.service'
DEBUG:systemctl:simple process for /usr/lib/systemd/system/mariadb.service
DEBUG:systemctl: pre-start done (OK) <->
DEBUG:systemctl:no status file: /var/run/mariadb.service.status
 returning {}
DEBUG:systemctl:ExecStart[0]: /usr/bin/mysqld_safe --basedir=/usr
DEBUG:systemctl:no status file: /var/run/mariadb.service.status
 returning {}
INFO:systemctl:simple start '/usr/bin/mysqld_safe' '--basedir=/usr'
DEBUG:systemctl:no status file: /var/run/mariadb.service.status
 returning {}
DEBUG:systemctl:writing to /var/run/mariadb.service.status
        MainPID=69
DEBUG:systemctl:simple process for /usr/lib/systemd/system/mariadb.service
INFO:systemctl:simple started PID 69
DEBUG:systemctl:  file time: 2020-04-12 13:11:34.641571
DEBUG:systemctl:  boot time: 2020-04-12 13:08:21.829391
DEBUG:systemctl:  file time: 2020-04-12 13:11:34.641571
DEBUG:systemctl:  boot time: 2020-04-12 13:08:21.829391
DEBUG:systemctl:reading /var/run/mariadb.service.status
DEBUG:systemctl:pid_file '/var/run/mariadb.service.status' => PID 69
INFO:systemctl:post-start '/usr/libexec/mariadb-wait-ready' '69'
DEBUG:systemctl:simple process for /usr/lib/systemd/system/mariadb.service

pid 69 is:
mysql       69    34  0 13:11 ?        00:00:00 [mysqld_safe] <defunct>

I don`t know what the problem is. Could you help me to fix it ?
Centos 7, mariadb-server 5.5.64

**Comment by gdraheim** [comment] 2020-04-12 17:55
I had been running MariDB on CentOS just fine, so it should not be much of a problem. However your line numbers do not quite match with my version. In any case, there is a ExecStartPost in your service descriptor that I have not seen before. That's probably the cause of the error as I dont'see a "post-start done" in the debug.log.

It could simply be that mariadb-wait-ready does not return simply because mariadb itself can not start succesfully. But that would be up to you to configure it correctly.

If you like to see it running then you can compare it to this scenario:

./testsuite.py test_8001 --image=centos:7.5.1804

**Comment by gzsmhf** [comment] 2020-04-13 03:05
I think i have fixed this error after checking debug info of mariadb. It records error message:
[ERROR] mysqld: Can't create/write to file '/var/run/mariadb/mariadb.pid' (Errcode: 2)
[ERROR] Can't start server: can't create PID file: No such file or directory

Then I manually create folder mariadb in /var/run and give 755, it can start successfully.
However when WSL restarts, the folder disappears by no reason. I think it is the wsl error. So in order to start mariadb, just create the folder every time after restarting wsl. 

Thank you for your help. really appreciate.

**Comment by gdraheim** [comment] 2020-04-18 08:49
It may have to do with the choice of /var/run as the base location while newer Linux versions will mount a special tmpfs /run which is picked up by systemd. There is always a symlink from /var/run to /run in that case but may be the WSL implementation is too strict in the interpretation of the systemd documentation - choosing to only mkdir /run in the container.

**Comment by gdraheim** [comment] 2020-08-09 10:03
I am closing this issue as it is basically a duplicate of #105

**Closed by gdraheim** 2020-08-09 10:03 UTC
