### ISSUE TITLE
sometimes fails to restart service

### ISSUE THREAD

**Issue by onlyjob** [gdraheim/docker-systemctl-replacement#11] opened 2017-09-13 07:45 UTC
~~~~
$ sudo /usr/local/bin/systemctl restart httpd
httpd[183]: [:error] [pid 183] AH00000: sd_notifyf returned an error -4
Traceback (most recent call last):
  File "/usr/local/bin/systemctl", line 2927, in <module>
    result = command_func(*modules)
  File "/usr/local/bin/systemctl", line 1612, in restart_modules
    return self.restart_units(units) and found_all
  File "/usr/local/bin/systemctl", line 1617, in restart_units
    if not self.restart_unit(unit):
  File "/usr/local/bin/systemctl", line 1626, in restart_unit
    return self.restart_unit_from(conf)
  File "/usr/local/bin/systemctl", line 1649, in restart_unit_from
    self.start_unit_from(conf)
  File "/usr/local/bin/systemctl", line 1301, in start_unit_from
    raise Exception("could not start service")
Exception: could not start service
~~~~

Spotted on CentOS-7.

FYI @colin-go.

**Comment by gdraheim** [comment] 2017-09-24 23:05
well, how to reproduce that? 

Actually, the man-page for "sd_notifyf" explains that the return code should be ignored. The -4 maps to errno = EINTR which simply says that the process got a signal() while being blocked (e.g. waiting for a file). So it looks more like Apache does it wrong.

I can however explain that because the standard systemd daemon has the notify-socket being open from start to end of the system uptime. The systemctl.py however does it only shortly for either start or stop calls. The only thing that might help is to make the notify_socket_from() function a singleton which it isn't currently.

**Comment by onlyjob** [comment] 2017-09-26 01:24
Problem happens after unsuccessful start. To reproduce break syntax of apache config, then `systemctl start httpd`. Then fix config and try `systemctl restart httpd`. 

As for `sd_notifyf` IMHO it is just a warning that have no practical implications without systemd...

**Comment by gdraheim** [comment] 2017-10-17 21:14
I have started to reproduce it in testcase 8011 where the httpd.conf is being reinstalled after some start/restart tests.

It works now because I have slightly changed the behaviour on a start-timeout - instead of throwing an exception it returns as False. Additionally it runs the ExecStopPost sequence as required by the systemd documentation - to differentiate the reason one may check the $SERVICE_RESULT variable which may be "timeout" after an unsuccessfull start or "success" on a plain stop.

**Comment by gdraheim** [comment] 2017-11-01 12:22
should be fixed.

**Closed by gdraheim** 2017-11-01 12:22 UTC
